# General
fix_outliers: true
standardized: false
output_format: csv
output_path: "./examples/xquad/csv-output"
rounding: 2

# Identifiers
score_col: "F1"
model_col: "Model"
task_col: "Language"

# Derive SDs from indices:
seed_sd_col: "SD_seed"
boot_sd_col: "SD_boot_avg"

# Resampling

## General
num_bootstrap_resamples: 100000

## Task resampling
task_resampling_method: "nonparametric"
task_resampling_with_replacement: true
task_resampling_num_tasks: 61

## Task resampling
replication_resampling_method: "parametric"

