# General
fix_outliers: true
standardized: false
output_format: csv
rounding: 2

# Identifiers
score_col: "Mean"
model_col: "Model"
task_col: "Task"

# SDs
replication_sd_col: "SD (boot)"

# Resampling

## General
num_bootstrap_resamples: 10000

## Task resampling
task_resampling_method: "nonparametric"
task_resampling_with_replacement: true
task_resampling_num_tasks: 61

## Task resampling
replication_resampling_method: "parametric"
