# General
fix_outliers: true
standardized: false
output_format: csv
rounding: 2

# Identifiers
score_col: "meta_score"
model_col: "submission_name"
task_col: "language"

# Derive SDs from indices:
replication_sd_col: "meta_score_std_dev"

# Resampling

## General
num_bootstrap_resamples: 10000

## Task resampling
task_resampling_method: "nonparametric"
task_resampling_with_replacement: true
task_resampling_num_tasks: 10

## Task resampling
replication_resampling_method: "parametric"
