# General
fix_outliers: true
standardized: false
output_format: csv
rounding: 2

# Identifiers
score_col: "F1"
model_col: "Model"
task_col: "Task"

# SDs
replication_idx_col: "Seed"
seed_idx_col: "Seed"
boot_idx_col: "Bootstrap"

# Resampling

## General
num_bootstrap_resamples: 10000

## Task resampling
task_resampling_method: "nonparametric"
task_resampling_with_replacement: true
task_resampling_num_tasks: 61

## Task resampling
replication_resampling_method: "nonparametric"
